export const dodomaLocations = [
  "Dodoma CBD",
  "Jakaya Kikwete Road",
  "Mlimwa Estate",
  "UDOM Campus",
  "Jamhuri Stadium",
  "Chang'ombe",
  "Makole Market",
  "Ipagala",
  "Uhuru Street",
  "Nyerere Road",
  "Kikuyu Area",
  "Railway Station",
];

export const locationCoordinates = {
  "Dodoma CBD": { lat: -6.1722, lng: 35.7395 },
  "Jakaya Kikwete Road": { lat: -6.18, lng: 35.74 },
  "Mlimwa Estate": { lat: -6.165, lng: 35.735 },
  "UDOM Campus": { lat: -6.19, lng: 35.75 },
  "Jamhuri Stadium": { lat: -6.16, lng: 35.73 },
  "Chang'ombe": { lat: -6.2, lng: 35.72 },
  "Makole Market": { lat: -6.155, lng: 35.745 },
  Ipagala: { lat: -6.175, lng: 35.755 },
  "Uhuru Street": { lat: -6.168, lng: 35.742 },
  "Nyerere Road": { lat: -6.182, lng: 35.738 },
  "Kikuyu Area": { lat: -6.152, lng: 35.748 },
  "Railway Station": { lat: -6.17, lng: 35.725 },
};

export const sampleRiders = [
  {
    name: "Juma Hassan",
    phone: "+255712345678",
    location: "Jakaya Kikwete Road",
    coordinates: locationCoordinates["Jakaya Kikwete Road"],
    status: "online",
    rating: 4.8,
    trips: 142,
    vehicleInfo: { plateNumber: "T 123 ABC", model: "Motorcycle" },
    earnings: 1250000,
    isIdentityVerified: true,
    isLicenseValid: true,
    hasInsurance: true,
    isPhoneVerified: true,
  },
  {
    name: "Baraka Mwita",
    phone: "+255754987321",
    location: "Mlimwa Estate",
    coordinates: locationCoordinates["Mlimwa Estate"],
    status: "on_trip",
    rating: 4.6,
    trips: 98,
    vehicleInfo: { plateNumber: "T 456 DEF", model: "Motorcycle" },
    earnings: 860000,
    isIdentityVerified: true,
    isLicenseValid: true,
    hasInsurance: true,
    isPhoneVerified: true,
  },
  {
    name: "Salim Abdallah",
    phone: "+255768111222",
    location: "UDOM Campus",
    coordinates: locationCoordinates["UDOM Campus"],
    status: "offline",
    rating: 4.9,
    trips: 210,
    vehicleInfo: { plateNumber: "T 789 GHI", model: "Motorcycle" },
    earnings: 2100000,
    isIdentityVerified: true,
    isLicenseValid: true,
    hasInsurance: true,
    isPhoneVerified: true,
  },
  {
    name: "Grace Mtembe",
    phone: "+255743555888",
    location: "Dodoma CBD",
    coordinates: locationCoordinates["Dodoma CBD"],
    status: "online",
    rating: 4.7,
    trips: 76,
    vehicleInfo: { plateNumber: "T 321 JKL", model: "Motorcycle" },
    earnings: 770000,
    isIdentityVerified: true,
    isLicenseValid: true,
    hasInsurance: true,
    isPhoneVerified: true,
  },
  {
    name: "Asha Mwinyi",
    phone: "+255712345001",
    location: "Nyerere Road",
    coordinates: locationCoordinates["Nyerere Road"],
    status: "online",
    rating: 4.5,
    trips: 64,
    vehicleInfo: { plateNumber: "T 654 MNO", model: "Motorcycle" },
    earnings: 560000,
    isIdentityVerified: true,
    isLicenseValid: true,
    hasInsurance: true,
    isPhoneVerified: true,
  },
];

export const sampleUsers = [
  {
    name: "Amina S.",
    phone: "+255712000001",
    defaultLocation: "Dodoma CBD",
    paymentMethods: ["M-Pesa"],
    provider: "local",
    email: null,
    googleId: null,
  },
];

export const seedTripBlueprints = [
  {
    customerPhone: "+255712000001",
    pickup: "Dodoma CBD",
    dropoff: "UDOM Campus",
    fare: 1800,
    status: "completed",
    paymentMethod: "M-Pesa",
    rating: 5,
    review: "Fast and safe ride.",
  },
  {
    customerPhone: "+255712000001",
    pickup: "Mlimwa Estate",
    dropoff: "Jamhuri Stadium",
    fare: 1600,
    status: "in_progress",
    paymentMethod: "Cash",
    rating: null,
    review: null,
  },
];
